# Generated by Django 4.2.4 on 2024-02-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('tee', models.CharField(max_length=20)),
                ('slope_rating', models.IntegerField()),
                ('course_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='GolfRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yards', models.IntegerField()),
                ('par', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)])),
                ('stroke_index', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)])),
                ('hole_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)])),
                ('hole_name', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.course')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('handedness', models.CharField(max_length=20)),
                ('championships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField()),
                ('stableford_score', models.IntegerField()),
                ('sandy', models.BooleanField(default=False)),
                ('golf_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.golfround')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_number', models.IntegerField()),
                ('resort_visit', models.IntegerField(null=True)),
                ('slug', models.SlugField(default='')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.resort')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_index', models.DecimalField(decimal_places=1, max_digits=3)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.holiday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player')),
            ],
        ),
        migrations.AddField(
            model_name='golfround',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.holiday'),
        ),
        migrations.AddField(
            model_name='course',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.resort'),
        ),
    ]
