# Generated by Django 4.2.4 on 2024-02-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='resort_visit',
        ),
    ]
