# Generated by Django 5.0.2 on 2024-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_score_stableford_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='stableford_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
