# Generated by Django 4.2.10 on 2024-02-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_score_stableford_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='handicap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.handicap'),
        ),
    ]
