# Generated by Django 4.2.10 on 2024-02-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_score_strokes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.holiday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player')),
            ],
        ),
    ]
