# Generated by Django 4.2.10 on 2024-02-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_playerholiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerHoliday',
        ),
    ]
