# Generated by Django 4.2.10 on 2024-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_delete_playerholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resort',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
