# Generated by Django 4.2.10 on 2024-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_resort_latitude_resort_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='resort',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
