# Generated by Django 4.2.10 on 2024-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_delete_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='highlight_link',
            field=models.ManyToManyField(blank=True, null=True, to='tournaments.video'),
        ),
    ]
