# Generated by Django 4.2.10 on 2024-03-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_score_highlight_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='highlight_link',
            field=models.ManyToManyField(blank=True, to='tournaments.video'),
        ),
    ]
