# Generated by Django 4.2.10 on 2024-03-26 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfround',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 0, 0)),
        ),
    ]
