# Generated by Django 5.0.2 on 2024-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_golfround_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
