# Generated by Django 4.2.10 on 2024-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='pro_tip',
            field=models.TextField(default='Pro Tip'),
            preserve_default=False,
        ),
    ]
