# Generated by Django 4.2.10 on 2024-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_hole_pro_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_tip', models.TextField(default='Pro Tip')),
            ],
        ),
        migrations.RemoveField(
            model_name='hole',
            name='pro_tip',
        ),
    ]
