# Generated by Django 4.2.10 on 2024-03-31 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_protip_remove_hole_pro_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='pro_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.protip'),
        ),
    ]
