# Generated by Django 4.2.10 on 2024-03-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_hole_pro_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='pro_tip',
        ),
        migrations.DeleteModel(
            name='ProTip',
        ),
    ]
