# Generated by Django 4.2.10 on 2024-03-31 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_remove_hole_pro_tip_delete_protip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_tip', models.TextField(default='Pro Tip')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.hole')),
            ],
        ),
    ]
