# Generated by Django 4.2.10 on 2024-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_protip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protip',
            name='hole',
        ),
        migrations.AddField(
            model_name='protip',
            name='hole',
            field=models.ManyToManyField(blank=True, to='tournaments.hole'),
        ),
    ]
