# Generated by Django 5.0.2 on 2024-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_remove_protip_hole_protip_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
