# Generated by Django 5.0.2 on 2024-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_player_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
