# Generated by Django 4.2.10 on 2024-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
