# Generated by Django 5.0.2 on 2024-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_score_match_play_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
