# Generated by Django 4.2.4 on 2024-02-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set_players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='player',
        ),
    ]
