# Generated by Django 4.2.4 on 2024-02-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_players', '0002_remove_holiday_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='handicap_index',
        ),
        migrations.AddField(
            model_name='course',
            name='course_rating',
            field=models.DecimalField(decimal_places=1, default=72, max_digits=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap_index', models.DecimalField(decimal_places=1, max_digits=3)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_players.holiday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_players.player')),
            ],
        ),
    ]
