# Generated by Django 4.2.4 on 2024-02-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_players', '0003_remove_player_handicap_index_course_course_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='holiday',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='set_players.holiday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='round',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='sandy',
            field=models.BooleanField(default=False),
        ),
    ]
