# Generated by Django 4.2.4 on 2024-02-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set_players', '0004_score_holiday_score_round_score_sandy'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resort',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='set_players.resort'),
            preserve_default=False,
        ),
    ]
